import React from 'react';

const Dashboard = () => {
    return (
        <div className='space-y-3'>
            <div id='sakib'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='sakib'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='sakib'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='sakib'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='sakib'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='sakib1'>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
            <div id='setting'>
                <h1 className='text-red-500 text-2xl'>success</h1>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis mollitia sed iure velit, alias exercitationem delectus corrupti corporis repellendus cum hic quos maxime voluptas necessitatibus dolorum impedit quae, autem eaque.</p>
            </div>
        </div>
    );
};

export default Dashboard;