import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: ['https://i.ibb.co/L1pGJBg/sakib2.png'],
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div>
          <Image src='https://i.ibb.co/L1pGJBg/sakib2.png' width={500} height={500} alt="" ></Image>
        </div>
      </body>

    </html>
  );
}
