import { Inter } from "next/font/google";
import "./globals.css";
import { Navlist } from "./components/Hearder/Hearder/links";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  throw Error("custom error")
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navlist></Navlist>
        {children}
        </body>
    </html>
  );
}
