import Head from 'next/head';
import VideoPlayer from './components/VideoPlayer';

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center flex-1 px-20 text-center">
        <h1 className="text-6xl font-bold mb-4">Welcome to My Next.js App</h1>
        <VideoPlayer />
      </main>
    </div>
  );
}
