import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Shared/Header/Header";
import Footer from "@/components/Shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-w-[1536px] mx-auto">
      <body className={inter.className}>
        <div className="relative top-[-40px]">
        <Header></Header>
        </div>
         <div className="mt-10">
         {children}
         </div>
        <Footer></Footer>
        </body>
    </html>
  );
}
