
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidevear from "@/components/Shared/LeftSidevear/LeftSidevear";
import style from "./layout.module.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
 

  return (
    <html lang="en" data-theme="black" className={style.demo}>
      
      <body className={inter.className}>
       <div className="mx-auto max-w-[1536px] flex bg-[#111113]  ">
          <div className="w-3/12">
               <LeftSidevear></LeftSidevear>
          </div>
          <div className="w-9/12 flex mr-5 bg-[#111113] overflow-scroll no-scrollbar mb-10  ">
            {children}
       </div>
       </div>
      </body>
    </html>
  );
}
