import Link from 'next/link';
import React from 'react';
export const metadata = {
  title: "App meta data",
  description: "Generated by create next app",
};


const LayoutAbout = ({ children }) => {
    return (
        <div>
         <nav className="text-2xl">
          <ul className="flex gap-4">
            <li><Link href="/about">About</Link></li>
            <li><Link href="/about/mission">Mission</Link></li>
          </ul>
        </nav>  
        {children}
        </div>
    );
};

export default LayoutAbout;